#!/usr/bin/env bash

set -e

DOCKER_RECIPE_BASE="$( cd "$(dirname "$0")" ; pwd -P )"
DOCKER_RECIPE_PATH=${DOCKER_RECIPE_PATH-"$DOCKER_RECIPE_BASE/recipes"}
DOCKER_RECIPE_OS=${DOCKER_RECIPE_OS-"debian"}

function docker_recipe() {
    for templateName in "${@}"; do
        # Resolve recipe file
        templateFiles=$(${DOCKER_RECIPE_BASE}/docker-recipe-find ${templateName})

        for templateSource in ${templateFiles}; do
            if [[ -x ${templateSource} ]]; then
                source ${templateSource}
                echo ""
                continue;
            fi

            "${DOCKER_RECIPE_BASE}/docker-recipe-parse" "${templateSource}"
            echo ""
        done
    done
}

if [[ -z "$1" ]];then
    if [[ -f "Dockerfile.recipe" ]]; then
        exec $0 Dockerfile.recipe > Dockerfile
        exit $?
    fi

    echo "Usage: $0 <package-name>"
    exit 1
fi

if [[ -x "$DOCKER_RECIPE_BASE/docker-recipe-$1" ]]; then
    # Subcommand
    cmd=$1
    shift
    exec "$DOCKER_RECIPE_BASE/docker-recipe-$cmd" ${*}
    exit $?
fi

if [[ -f "$1" ]]; then
    ${DOCKER_RECIPE_BASE}/docker-recipe-parse $1
    exit $?
fi

docker_recipe "${@}"

# grep apt Dockerfile | grep '\-y' | cut -d'y' -f2- | cut -d'>' -f1 | xargs echo 'RUN apt-purge -y'
